export const ROOT_ID = '__ROOT_ID__';
export const PLAYING_FIELD_DIMENSION_ID = '__PLAYING_FIELD_DIMENSION_ID__';
export const WINNING_STREAK_DIMENSION_ID = '__WINNING_STREAK_DIMENSION_ID__';
export const SETTINGS_FORM_ID = '__SETTINGS_FORM_ID__';
export const GAME_BOARD_HTML_ELEMENT_ID = '__GAME_BOARD_ID__';
export const RELOAD_GAME_BUTTON_ID = '__RELOAD_GAME_BUTTON_ID__';