export const ROOT_ID = '__ROOT_ID__';
export const PLAYING_FIELD_DIMENSION_ID = '__PLAYING_FIELD_DIMENSION_ID__';
export const WINNING_STREAK_DIMENSION_ID = '__WINNING_STREAK_DIMENSION_ID__';
export const SETTINGS_FORM_ID = '__SETTINGS_FORM_ID__';
export const GAME_BOARD_ID = '__GAME_BOARD_ID__';