export const PLAYING_FIELD_DIMENSION_ID = '__PLAYING_FIELD_DIMENSION_ID__';
export const WINNING_STREAK_DIMENSION_ID = '__WINNING_STREAK_DIMENSION_ID__';
export const SETTINGS_FORM_ID = '__SETTINGS_FORM_ID__';